### ISSUE TITLE
Error: process.stdout cannot be closed.

### ISSUE THREAD

**Issue by mielvds** [RubenVerborgh/HDT-Node#4]
When executing  `hdt /data/dbpedia/data_3_9.hdt --query '?s ?p ?o' --offset 200 --limit 100 --format turtle` , the following error occurs:

    ...
        <http://dbpedia.org/property/title> "Feel Good Hit of the Fall"@en, "Hammerhead"@en, "Intensify"@en.
    events.js:141
          throw er; // Unhandled 'error' event
          ^
  
    Error: process.stdout cannot be closed.
        at WriteStream.stdout.destroy.stdout.destroySoon (node.js:631:20)
        at WriteStream.onSocketFinish (net.js:196:17)
        at emitNone (events.js:67:13)
        at WriteStream.emit (events.js:166:7)
        at finishMaybe (_stream_writable.js:468:14)
        at afterWrite (_stream_writable.js:347:3)
        at doNTCallbackMany (node.js:461:18)
        at process._tickCallback (node.js:359:17)

**Comment by RubenVerborgh** [comment]
Thanks for reporting, fixed!

**Comment by mielvds** [comment]
yw :)

**Comment by mielvds** [comment]
Could this be included in a npm release?

**Comment by RubenVerborgh** [comment]
Published as v1.2.4.
